
GET http://localhost:8080/users

###

GET http://localhost:8080/user


{
    "userId": "628e3af0b7a2ccc7e5f921e5"
}
###

POST http://localhost:8080/user
Content-Type: application/json

{
    "validationAnswer": "REMO",
    "username": "Rune Klam",
    "password": "smukke1234"
}

###
//
//               SKAL FIXES          1
//
PATCH http://localhost:8080/user
Content-Type: application/json

{
    "userId": "6284a5f3c2fd93fa6b325566",
    "firstname": "Søren"
}

###

DELETE http://localhost:8080/user
Content-Type: application/json

{
    "userId": "6284a5f3c2fd93fa6b325566"
}

###

GET http://localhost:8080/posts

###


GET http://localhost:8080/post
Content-Type: application/json

{
    "postId": "627eabc9ab022a89e69b0331"
}

###

POST http://localhost:8080/post
Content-Type: application/json

{
    "text": "Se mit nye, fede sæt",
    "username": "SpørgeSøren",
    "userId": "628e3af0b7a2ccc7e5f921e5"
}

###

DELETE http://localhost:8080/post
Content-Type: application/json

{
    "postId": "6288eca92f5dc7f1a8f76e4f"
}

###

PATCH http://localhost:8080/post
Content-Type: application/json

{
    "postId": "627eabc9ab022a89e69b0331",
    "text": "God aften"
}

###

DELETE http://localhost:8080/post
Content-Type: application/json

{
    "postId": "6284d81709c9b418bc5afbce"
}

###

POST http://localhost:8080/comment
Content-Type: application/json

{
    "postId": "6290a04c6c18b1332e376ef6",
    "text": "For Søren det er flot, mand!!",
    "username": "SKP",
    "userId": "627cf4e145a41ea52c4540d2"
}

###

PATCH http://localhost:8080/comment
Content-Type: application/json

{
    "commentId": "6282b5e809d694780b1c5090",
    "text": "Jeg kan faktisk bedre lide ggggggg"
}

###

POST http://localhost:8080/comment/like
Content-Type: application/json

{
    "postId": "6288eca92f5dc7f1a8f76e4f",
    "commentId": "6288eca92f5dc7f1a8f76e50",
    "userId": "6279158a064e0019c5fc4f2c",
    "username": "KalleKalle"
}

###

DELETE http://localhost:8080/comment/like
Content-Type: application/json

{
    "postId": "6288eca92f5dc7f1a8f76e4f",
    "commentId": "6288eca92f5dc7f1a8f76e50",
    "userId": "6279158a064e0019c5fc4f2c"
}

###


POST http://localhost:8080/comment/quote
Content-Type: application/json 

{
    "postId": "628f71c16c4c10df3b72be2f",
    "quotetCommentId": "62908b0b6a359083a669c02f",
    "quotetCommentText": "Yes sir",
    "quotetCommentUserId": "628e3c0ef24148cf460a1671",
    "quotedCommentUsername": "SpørgeSøren",
    "newCommentText": "Yes sir",
    "newCommentUserId": "628e3c0ef24148cf460a1671",
    "newCommentUsername": "SpørgeSøren"
}

###



###

GET http://localhost:8080/posts
